#!/bin/bash
VM_USER=argus

# IOMMU_GPU="2f:00.0"
IOMMU_GPU="2d:00.0"
IOMMU_GPU_AUDIO="2d:00.1"
# VIRSH_GPU=pci_0000_2f_00_0
VIRSH_GPU=pci_0000_2d_00_0
VIRSH_AUDIO=pci_0000_2d_00_1

# videoid="1002 731f"
videoid="10de 1180"
audioid="10de 0e0a"

RAM=10G
CORES=4

SIZE="100G"
ISO_PATH=enterprise.iso
VIRTIO_PATH=virtio.iso
WINDOWS_IMG="disk_image"
ROMFILE="AMD_Radeon_RX_5700_Navi_10_017-001-000-042-012565.rom"

LOG=./qemu-log.txt

OVMF=/etc/ovmf/OVMF_CODE.fd
OVMF_VARS=/etc/ovmf/OVMF_VARS.fd

## Ulimit
ULIMIT=$(ulimit -a | grep "max locked memory" | awk '{print $6}')
ULIMIT_TARGET=$(( $(echo $RAM | tr -d 'G')*1048576+100000 ))
